apiVersion: v1
kind: ServiceAccount
metadata:
  name: frames
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frames
spec:
  template:
    spec:
      initContainers:
        - name: template-quorum-key
          image: ghcr.io/tkhq/frames:sha-c072a515be4b9b28ebf7a51766f1b9e8fe9174d7
          env:
            - name: TURNKEY_SIGNER_ENVIRONMENT
              value: "prod"
          command:
            - sh
            - -c
            - |
                mkdir -p templated/import && envsubst '${TURNKEY_SIGNER_ENVIRONMENT}' < import/index.template.html > templated/import/index.html;
                mkdir -p templated/import && envsubst '${TURNKEY_SIGNER_ENVIRONMENT}' < import/standalone.template.html > templated/import/standalone.html;
                mkdir -p templated/export && envsubst '${TURNKEY_SIGNER_ENVIRONMENT}' < export/index.template.html > templated/export/index.html;
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - name: templated
              mountPath: /usr/share/nginx/templated
      containers:
        - name: frames
          image: ghcr.io/tkhq/frames:sha-c072a515be4b9b28ebf7a51766f1b9e8fe9174d7
          ports:
            - name: auth
              containerPort: 8080
            - name: export
              containerPort: 8081
            - name: recovery
              containerPort: 8082
            - name: import
              containerPort: 8083
          livenessProbe:
            httpGet:
              path: /health
              port: auth
          resources:
            requests:
              memory: 5Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - name: templated
              mountPath: /usr/share/nginx/templated
              readOnly: true
      serviceAccountName: frames
      volumes:
        - name: templated
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: frames
spec:
  ports:
    - name: http-auth
      port: 8080
      targetPort: auth
    - name: http-export
      port: 8081
      targetPort: export
    - name: http-recovery
      port: 8082
      targetPort: recovery
    - name: http-import
      port: 8083
      targetPort: import
