apiVersion: v1
kind: ServiceAccount
metadata:
  name: frames
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frames
spec:
  template:
    spec:
      containers:
        - name: frames
          image: ghcr.io/tkhq/frames
          ports:
            - name: recovery
              containerPort: 8080
            - name: export
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /health
              port: recovery
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
      serviceAccountName: frames
---
apiVersion: v1
kind: Service
metadata:
  name: frames
spec:
  ports:
    - name: http-recovery
      port: 8080
      targetPort: recovery
    - name: http-export
      port: 8081
      targetPort: export
