apiVersion: v1
kind: ServiceAccount
metadata:
  name: frames
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frames
spec:
  template:
    spec:
      containers:
        - name: frames
          image: ghcr.io/tkhq/frames
          ports:
            - name: auth
              containerPort: 8080
            - name: export
              containerPort: 8081
            - name: recovery
              containerPort: 8082
          livenessProbe:
            httpGet:
              path: /health
              port: auth
          resources:
            requests:
              memory: 5Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
      serviceAccountName: frames
---
apiVersion: v1
kind: Service
metadata:
  name: frames
spec:
  ports:
    - name: http-auth
      port: 8080
      targetPort: auth
    - name: http-export
      port: 8081
      targetPort: export
    - name: http-recovery
      port: 8082
      targetPort: recovery
